version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: examsoffice2021
      POSTGRES_DB: studentDB
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pgnet

  db-backup:
    image: postgres:16
    container_name: postgres-backup
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: studentDB
      PGUSER: postgres
      PGPASSWORD: examsoffice2021
      BACKUP_INTERVAL: 21600   # 6 hours (in seconds)
    volumes:
      - /home/mebinwobi/Documents/examsoffice/postgres_backups:/backups
      - /home/mebinwobi/Documents/examsoffice/backup.sh:/backup.sh:ro
    command: ["/bin/bash", "/backup.sh"]
    networks:
      - pgnet

  backup-sync:
    image: rclone/rclone:latest
    container_name: backup-sync
    restart: unless-stopped
    volumes:
      - /home/mebinwobi/Documents/examsoffice/postgres_backups:/backups:ro
      - /home/mebinwobi/.config/rclone:/config/rclone:ro
    command: >
      sh -c '
      while true; do
        echo "[$$(date)] Syncing backups...";
        rclone copy /backups gdrive:studentDB_backups \
          --config /config/rclone/rclone.conf \
          --create-empty-src-dirs;
        sleep 600;
      done
      '
      networks:
        - pgnet

  web:
      build:
        context: /home/mebinwobi/Documents/examsoffice
        dockerfile: /home/mebinwobi/Documents/examsoffice/examsoffice/Dockerfile
      container_name: django
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - /home/mebinwobi/Documents/examsoffice:/app
      ports:
        - "8005:8000"
      depends_on:
        - db
      environment:
        - DJANGO_SETTINGS_MODULE=examsoffice.settings
      restart: unless-stopped
      networks:
        - pgnet

volumes:
  pgdata:

networks:
  pgnet:

